;;; ashen-theme.el --- Ashen color scheme -*- lexical-binding: t; -*-

(deftheme ashen "Ashen color scheme")

(let ((background "#121212")
      (foreground "#b4b4b4")
      (red-flame "#c53030")
      (red-glowing "#df6464")
      (red-ember "#b14242")
      (orange-glow "#d87c4a")
      (orange-blaze "#c4693d")
      (orange-smolder "#e49a44")
      (orange-golden "#e5a72a")
      (brown "#89492a")
      (dark-brown "#322119")
      (blue "#4a8b8b")
      (g-1 "#e5e5e5")
      (g-2 "#d5d5d5")
      (g-3 "#b4b4b4")
      (g-4 "#a7a7a7")
      (g-5 "#949494")
      (g-6 "#737373")
      (g-7 "#535353")
      (g-8 "#323232")
      (g-9 "#212121")
      (g-10 "#1d1d1d")
      (g-11 "#191919")
      (g-12 "#151515"))

  (custom-theme-set-faces
   'ashen
   `(default ((t :background ,background :foreground ,foreground)))
   `(cursor ((t :background ,g-5)))
   `(fringe ((t :background ,g-9)))
   `(region ((t :background ,g-8)))
   `(highlight ((t :background ,g-11)))
   `(minibuffer-prompt ((t :foreground ,blue :weight bold)))
   `(font-lock-builtin-face ((t :foreground ,blue)))
   `(font-lock-comment-face ((t :foreground ,g-7 :slant italic)))
   `(font-lock-comment-delimiter-face ((t :foreground ,g-7 :slant italic)))
   `(font-lock-constant-face ((t :foreground ,blue)))
   `(font-lock-function-name-face ((t :foreground ,foreground :weight bold)))
   `(font-lock-function-call-face ((t :foreground ,foreground)))
   `(font-lock-variable-name-face ((t :foreground ,foreground)))
   `(font-lock-variable-use-face ((t :foreground ,foreground)))
   `(font-lock-keyword-face ((t :foreground ,red-ember)))
   `(font-lock-string-face ((t :foreground ,red-glowing)))
   `(font-lock-doc-face ((t :foreground ,red-glowing)))
   `(font-lock-doc-markup-face ((t :foreground ,orange-smolder)))
   `(font-lock-type-face ((t :foreground ,blue)))
   `(font-lock-number-face ((t :foreground ,blue)))
   `(font-lock-operator-face ((t :foreground ,orange-blaze)))
   `(font-lock-delimiter-face ((t :foreground ,orange-smolder)))
   `(font-lock-bracket-face ((t :foreground ,g-6)))
   `(font-lock-punctuation-face ((t :foreground ,g-2)))
   `(font-lock-misc-punctuation-face ((t :foreground ,orange-golden)))
   `(font-lock-escape-face ((t :foreground ,orange-smolder)))
   `(font-lock-negation-char-face ((t :foreground ,orange-blaze)))
   `(font-lock-property-name-face ((t :foreground ,orange-blaze)))
   `(font-lock-property-use-face ((t :foreground ,orange-blaze)))
   `(font-lock-preprocessor-face ((t :foreground ,orange-smolder)))
   `(font-lock-warning-face ((t :foreground ,orange-golden :weight bold)))
   `(mode-line ((t :foreground ,foreground :background ,g-9)))
   `(mode-line-inactive ((t :foreground ,g-3 :background ,g-9)))
   `(line-number ((t :foreground ,foreground :background ,g-11)))
   `(line-number-current-line ((t :foreground ,foreground :background ,g-8)))
   `(dired-directory ((t :foreground ,orange-glow)))
   `(dired-symlink ((t :foreground ,red-ember)))
   `(dired-ignored ((t :foreground ,g-5)))
   `(org-level-1 ((t :foreground ,orange-glow :weight bold)))
   `(org-level-2 ((t :foreground ,orange-blaze)))
   `(org-level-3 ((t :foreground ,orange-glow)))
   `(org-block ((t :background ,g-11)))
   `(org-code ((t :foreground ,orange-blaze)))
   `(error ((t :foreground ,red-flame :weight bold)))
   `(warning ((t :foreground ,orange-golden :weight bold)))
   `(success ((t :foreground ,orange-blaze :weight bold)))
   `(isearch ((t :foreground ,orange-blaze :background ,g-11 :inverse-video t)))
   `(lazy-highlight ((t :foreground ,orange-smolder :background ,g-11 :inverse-video t)))
   `(link ((t :foreground ,blue :underline t)))
   `(link-visited ((t :foreground ,red-ember :underline t)))
   `(show-paren-match ((t :background ,g-6 :foreground ,g-12)))
   `(show-paren-mismatch ((t :background ,red-flame :foreground ,g-12)))
   `(eglot-inlay-hint-face ((t :foreground ,g-6 :height 0.8 :slant italic)))
   `(eglot-type-hint-face ((t :inherit eglot-inlay-hint-face)))
   `(eglot-parameter-hint-face ((t :inherit eglot-inlay-hint-face)))
   `(tree-sitter-hl-face:attribute ((t :foreground ,g-4 :slant italic)))
   `(tree-sitter-hl-face:comment ((t :foreground ,g-7 :slant italic)))
   `(tree-sitter-hl-face:comment.block.documentation ((t :foreground ,g-7 :slant italic)))
   `(tree-sitter-hl-face:comment.unused ((t :foreground ,g-7 :slant italic :strike-through t)))
   `(tree-sitter-hl-face:conceal ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:constructor ((t :foreground ,g-1)))
   `(tree-sitter-hl-face:constant ((t :foreground ,orange-blaze)))
   `(tree-sitter-hl-face:constant.builtin ((t :foreground ,blue)))
   `(tree-sitter-hl-face:constant.builtin.boolean ((t :foreground ,blue)))
   `(tree-sitter-hl-face:constant.character ((t :foreground ,red-glowing :weight bold)))
   `(tree-sitter-hl-face:constant.character.escape ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:constant.macro ((t :foreground ,blue)))
   `(tree-sitter-hl-face:constant.numeric ((t :foreground ,blue)))
   `(tree-sitter-hl-face:diff.delta ((t :foreground ,brown)))
   `(tree-sitter-hl-face:diff.minus ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:diff.plus ((t :foreground ,g-6)))
   `(tree-sitter-hl-face:error ((t :foreground ,red-flame)))
   `(tree-sitter-hl-face:function ((t :foreground ,g-3 :weight bold)))
   `(tree-sitter-hl-face:function.builtin ((t :foreground ,g-3 :weight bold :slant italic)))
   `(tree-sitter-hl-face:function.call ((t :foreground ,g-3)))
   `(tree-sitter-hl-face:function.macro ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:hint ((t :foreground ,g-4)))
   `(tree-sitter-hl-face:info ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:keyword ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:keyword.conditional ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:keyword.control.conditional ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:keyword.control.directive ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:keyword.control.import ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:keyword.directive ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:keyword.operator ((t :foreground ,orange-blaze)))
   `(tree-sitter-hl-face:keyword.storage ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:keyword.storage.modifier ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:keyword.storage.modifier.mut ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:keyword.storage.modifier.ref ((t :foreground ,red-ember :slant italic)))
   `(tree-sitter-hl-face:label ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:markup.bold ((t :weight bold)))
   `(tree-sitter-hl-face:markup.heading ((t :foreground ,red-glowing :weight bold)))
   `(tree-sitter-hl-face:markup.italic ((t :slant italic)))
   `(tree-sitter-hl-face:markup.link.label ((t :foreground ,red-ember)))
   `(tree-sitter-hl-face:markup.link.text ((t :foreground ,red-glowing)))
   `(tree-sitter-hl-face:markup.link.uri ((t :foreground ,red-glowing :slant italic :underline t)))
   `(tree-sitter-hl-face:markup.link.url ((t :foreground ,red-glowing :slant italic :underline t)))
   `(tree-sitter-hl-face:markup.list ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:markup.list.checked ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:markup.list.numbered ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:markup.list.unchecked ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:markup.list.unnumbered ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:markup.quote ((t :slant italic)))
   `(tree-sitter-hl-face:markup.raw.block ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:markup.raw.inline ((t :foreground ,g-2 :background ,g-10)))
   `(tree-sitter-hl-face:markup.strikethrough ((t :strike-through t)))
   `(tree-sitter-hl-face:method.call ((t :foreground ,g-3)))
   `(tree-sitter-hl-face:namespace ((t :foreground ,orange-glow :weight bold)))
   `(tree-sitter-hl-face:number ((t :foreground ,blue)))
   `(tree-sitter-hl-face:operator ((t :foreground ,orange-blaze)))
   `(tree-sitter-hl-face:property ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:property.definition ((t :foreground ,orange-glow :weight bold)))
   `(tree-sitter-hl-face:punctuation ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:punctuation.bracket ((t :foreground ,g-6)))
   `(tree-sitter-hl-face:punctuation.delimiter ((t :foreground ,orange-smolder)))
   `(tree-sitter-hl-face:punctuation.special ((t :foreground ,orange-golden)))
   `(tree-sitter-hl-face:special ((t :foreground ,orange-smolder)))
   `(tree-sitter-hl-face:string ((t :foreground ,red-glowing)))
   `(tree-sitter-hl-face:string.escape ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:string.regexp ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:string.special ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:string.special.path ((t :foreground ,red-glowing :weight bold)))
   `(tree-sitter-hl-face:string.special.symbol ((t :foreground ,orange-smolder)))
   `(tree-sitter-hl-face:string.special.url ((t :foreground ,red-glowing :weight bold)))
   `(tree-sitter-hl-face:string.symbol ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:tag ((t :foreground ,orange-glow :slant italic)))
   `(tree-sitter-hl-face:type ((t :foreground ,blue)))
   `(tree-sitter-hl-face:type.argument ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:type.builtin ((t :foreground ,blue)))
   `(tree-sitter-hl-face:type.enum.variant ((t :foreground ,orange-blaze)))
   `(tree-sitter-hl-face:type.enum.variant.builtin ((t :foreground ,orange-blaze)))
   `(tree-sitter-hl-face:type.parameter ((t :foreground ,orange-glow)))
   `(tree-sitter-hl-face:variable ((t :foreground ,g-3)))
   `(tree-sitter-hl-face:variable.builtin ((t :foreground ,blue)))
   `(tree-sitter-hl-face:variable.other.member ((t :foreground ,g-2)))
   `(tree-sitter-hl-face:variable.parameter ((t :foreground ,g-2 :slant italic)))
   `(tree-sitter-hl-face:warning ((t :foreground ,orange-golden)))
   `(tooltip ((t :background ,g-9 :foreground ,foreground :box (:line-width 1 :color ,g-6))))
   `(scroll-bar ((t :background ,g-10 :foreground ,g-7)))
   `(widget ((t :background ,g-10 :foreground ,foreground)))
   `(widget-field ((t :background ,g-9 :foreground ,foreground)))
   `(menu ((t :background ,g-10 :foreground ,foreground)))
   `(menu-selection ((t :background ,g-4 :foreground ,foreground)))
   `(secondary-selection ((t :background ,g-11 :foreground ,g-3)))
   `(shadow ((t :foreground ,g-7)))
   `(vertical-border ((t :foreground ,g-7)))
   `(header-line ((t :background ,g-9 :foreground ,g-5)))
   `(button ((t :background ,g-8 :foreground ,foreground :box (:line-width 2 :color ,g-7))))
   `(completions-common-part ((t :foreground ,g-6)))
   `(completions-first-difference ((t :foreground ,foreground :weight bold)))
   `(completions-annotations ((t :foreground ,g-5 :slant italic)))
   `(completions-group-title ((t :foreground ,orange-glow :weight bold)))
   `(completions-highlight ((t :background ,g-4))))
  (provide-theme 'ashen))
